# Generated by Django 2.2 on 2021-12-08 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_author_blog_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
